### ISSUE TITLE
npm cdn bundle contains build stuff

### ISSUE THREAD

**Issue by dafanasiev** [AppsFlyerSDK/react-native-appsflyer#58] opened 2018-11-16 15:30 UTC
`android/build/` folder inside https://registry.npmjs.org/react-native-appsflyer/-/react-native-appsflyer-1.2.13.tgz  - please exclude it (and also other "build stuff")

**Comment by julo15** [comment] 2018-12-08 21:46
This issue is actually incredibly problematic. In our project, it looks like this issue has been the cause of  Android Studio failing to sync with gradle properly (Android Studio 3.1.4). Luckily this does not seem to affect command-line building, so our CI has been unaffected.

@dafanasiev Not sure if you were running into the same problem as us. But until this is fixed by the owners here, here's a workaround for the Android Studio problem:
1) Install [patch-package](https://www.npmjs.com/package/patch-package)
2) Patch `react-native-appsflyer` by removing `android.iml`, `react-native-appsflyer.iml`, `.gradle/` and `.idea/` from `node_modules/react-native-appsflyer/android`.
3) Run `yarn patch-package react-native-appsflyer` (or the npm equivalent, if you're using npm) to complete the patch.
4) Check in the generated file in the `patches/` directory into your source control.

After that, Android Studio should successfully sync with gradle.

**Closed** 2019-11-13 10:05 UTC
