### ISSUE TITLE
onInstallConversionData dosen't return onAppOpenAttribution when mounting

### ISSUE THREAD

**Issue by katjastrof** [AppsFlyerSDK/react-native-appsflyer#53] opened 2018-10-12 08:11 UTC
I get a success callback from **onInstallConversionData** every time opening the app. I can get both callbacks of type  **onInstallConversionDataLoaded** and **onAppOpenAttribution**.  
But I don't get the  **onAppOpenAttribution**  when mounting the app for the first time even if I pressed a referal-link.
 If I have the app running in background and pressing the referallink I get an **onAppOpenAttribution** callback. If I open the app with the link and then open it from the background I get the **onAppOpenAttribution** when opening from background. 

Do you now if this is how it suppose to be?

**Comment by af-fess** [comment] 2018-10-14 06:52
hey @katjastrof , are we talking about Android or iOS (+ OS version)? also please provide relevant code snippets of integration with AppsFlyer SDK.
Thank you,

**Comment by katjastrof** [comment] 2018-10-15 08:32
I'm using Android. I'm using the react-native-appsflyer 1.2.13 and the Android OS I've tested on is 7 and 8.

`  appsFlyer.onInstallConversionData(result => {
      if (
        result.status == 'success'
      ) {
        console.log(result)
      }
    })
    const options = {
      devKey: AF_DEV_KEY,
      isDebug: true,
    }
    appsFlyer.initSdk(
      options,
      result => {
        console.log(result)
      },
      error => {
        console.error(error)
      }
    )`

 It's the `appsFlyer.onInstallConversionData(result => {})` which gives a success callback when opening app. But the result type differs between being an  **onInstallConversionDataLoaded**  and **onAppOpenAttribution**.   The problem I have is when I mounting the app from an referal link I get the type  **onInstallConversionDataLoaded** . If I put the app in background and reopen it I get the **onAppOpenAttribution**.  If I have the app running from start in background and open from the same referallink I get **onAppOpenAttribution** directly.

**Comment by bfinamore** [comment] 2019-01-02 04:13
I'm also experiencing this issue. When clicking a deeplink, `onInstallDataLoaded` event is consistently fired on launch/foreground, but `onAppOpenAttribution` only seems to be fired when the app is already running in the background prior to deeplink click, and NOT if the app is started up fresh. Also can confirm that backgrounding/foregrounding does then trigger `onAppOpenAttribution` in the fresh launch case. I have reproduced this behavior on both Android and iOS. Has anyone figured out a resolution or work-around for this? 

Here's my implementation along with some log outputs for the various cases:

https://gist.github.com/bfinamore/a5e5c2f94861b7d49ee5f05f91223ae0

**Comment by af-fess** [comment] 2019-01-23 17:55
Will be fixed in next week v1.4.0

**Comment by santiph** [comment] 2019-02-04 11:04
@af-fess is there any update on v1.4.0?

**Comment by af-fess** [comment] 2019-02-05 05:36
@santiph we have a fix on the native side of SDK. So we are going to release Android `4.8.20` and next after - RN 1.4.0. 

We already tested it with the beta version and everything works as expected.

Thank you,

**Comment by af-fess** [comment] 2019-02-07 16:44
@katjastrof we tested a staging version, so far you can try this branch:

```
$ react-native install https://github.com/AppsFlyerSDK/react-native-appsflyer#dev/RD-16299/deeplink-oaoa-fix
```

**Comment by af-fess** [comment] 2019-02-18 09:35
#71 solved, https://github.com/AppsFlyerSDK/react-native-appsflyer/blob/master/CHANGELOG.md

**Closed by af-fess** 2019-02-18 09:35 UTC
Labels: bug

**Comment by tete7** [comment] 2019-05-07 16:30
I am not sure if it's solved I am facing that issue already: 
When the app is already installed I get a succesful callback from onAppOpenAtrtribution method but if I do the test mentioned here there's no callback: https://support.appsflyer.com/hc/en-us/articles/208874366-OneLink-Deep-Linking-Guide#urls-testing-testing-deferred-deep-linking-for-scheme-uris. Which basically consists on uninstalling the app click the deep link and launch the app from the simulator.

DeepLink: https://goin.onelink.me/xcGq/1977c4de
react-native-appsflyer: 1.4.1
react-native: 0.55.4

**Comment by aznj** [comment] 2019-07-02 06:04
This is happening on android sdk as well, and I believe they don't have fix for it yet.
